datasource:
  url: jdbc:postgresql://localhost:5432/tttt
  username: postgres
  password: root

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351

superuser:
  id: 1
  enabled: true
  default:
    password: superuser