spring:
  profiles:
    default: local

  datasource:
    url: jdbc:postgresql://host.docker.internal:5433/tttt
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml


superuser:
  id: 1
  enabled: true
  default:
    password: superuser