spring:
  profiles:
    default: local

  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml


superuser:
  id: 1
  enabled: true
  default:
    password: superuser