datasource:
  url: ${DB_URL}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

token:
  signing:
    key: ${TOKEN_KEY}

superuser:
  id: 1
  enabled: ${SUPERUSER_ENABLE}
  default:
    password: ${SUPERUSER_PASSWORD}