spring:
  profiles:
    default: local

  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

superuser:
  id: ${superuser.id}
  enabled: ${superuser.enabled}
  default:
    password: ${superuser.password}
