version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: wishlist_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: ..
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/wishlist_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - TOKEN_KEY=413F4428472B4B6250655368566D5970337336763979244226452948404D6352
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"


  grafana:
    image: grafana/grafana
    ports:
      - "4000:4000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  db_data:
